/**
 * File Synchronization Script
 *
 * One-way sync from laptop (source) to external disks (destinations).
 * Source files are NEVER modified or deleted.
 *
 * USAGE:
 * 1. Create configurations/sync.config.js (see config format below), or pass a config with --config / --config-files
 * 2. Run: node run-sync.js
 * 3. Optional flags:
 *    - node run-sync.js --dry-run (preview changes without applying)
 *    - node run-sync.js --allow-remove (delete files in dest that don't exist in source)
 *    - node run-sync.js --with-hash (enable hash comparison for same-size files)
 *    - node run-sync.js --config=custom.config.js (use custom folder config file)
 *    - node run-sync.js --config-files=YYYY-MM-DD-HH-MM-SS-sync-config-files.js (use file mapping config)
 *    - node run-sync.js --modified-time-threshold=2s (how much newer the source must be to count as changed,
 *      in milliseconds or with an "s"/"ms" suffix; overrides settings.modifiedTimeThresholdMs from the config;
 *      default 2s, for FAT32/exFAT disks that keep 2 second times)
 *    - node run-sync.js --config=inspect.config.js --mapping=2 (or --mapping=1,3) syncs only those mappings of a
 *      folder config, numbered from 1 in the config order. Without it, mappings with "enabled: false" are skipped.
 *    - node run-sync.js --triggered-by="schedule: general schedule" (written in the log header, used by the scheduler)
 *
 * Logs are never overwritten: when two runs finish in the same second, the second log gets a "-2" suffix.
 *
 * CONFIG PATHS:
 * - --config and --config-files are resolved from the current folder first, then from the "configurations" folder,
 *   where run-inspect-folders.js saves the generated configs.
 *
 * AUTO-DETECTION (when no --config or --config-files is given):
 * - If configurations/sync-config-files.js exists: syncs only listed files (file-by-file mode)
 * - Otherwise: uses configurations/sync.config.js and scans folders normally
 *
 * FILE MAPPING CONFIG (sync-config-files.js, as generated by run-inspect-folders.js):
 * module.exports = {
 *     settings: {modifiedTimeThresholdMs: 2000},
 *     files: {
 *         "C:\\source\\file.pdf": ["X:\\backup-1\\file.pdf", "Y:\\backup-2\\file.pdf"],
 *         "C:\\source\\other.pdf": "Y:\\backup-2\\other.pdf"
 *     }
 * };
 * Older file lists without "settings" and "files" (only the source to destinations object) still work.
 *
 * STOPPING:
 * - Ctrl+C, closing the console window, or the "stop" IPC message when started with child_process.fork()
 *   (used by the web tool).
 * - All of them save the log before exiting.
 *
 * CONFIGURATION (configurations/sync.config.js, settings is optional):
 * module.exports = {
 *     settings: {modifiedTimeThresholdMs: 2000},
 *     mappings: [
 *         {
 *             from: "C:\\source\\activities",
 *             to: ["Y:\\backup-2\\activities"],
 *             enabled: true,
 *             includeExtensions: [".fit", ".gpx"],
 *             excludeExtensions: [".tmp"],
 *             maxSizeBytes: 0,
 *             excludeHidden: true,
 *             excludeSystem: true,
 *             excludeNames: ["node_modules", ".git"]
 *         }
 *     ]
 * };
 */

const fs = require('fs');
const fsp = require('fs').promises;
const path = require('path');
const crypto = require('crypto');

class RunSync
{

    constructor()
    {
        this.startTime = Date.now();
        this.errors = [];
        this.filesPlanned = 0;
        this.filesProcessed = 0;
        this.alreadySyncedFiles = [];
        this.syncedFiles = [];
        this.removedFiles = [];
        this.args = process.argv.slice(2);
        this.allowRemove = -1 !== this.args.indexOf('--allow-remove');
        this.dryRun = -1 !== this.args.indexOf('--dry-run');
        this.withHash = -1 !== this.args.indexOf('--with-hash');
        // FAT32 and exFAT copies made by other tools often keep the modified time with 2 second precision:
        this.defaultModifiedTimeThresholdMs = 2000;
        this.cliModifiedTimeThresholdMs = this.parseModifiedTimeThreshold();
        this.modifiedTimeThresholdMs = this.defaultModifiedTimeThresholdMs;
        this.selectedMappings = this.parseMappingSelection();
        this.triggeredBy = this.parseTextArg('--triggered-by=');
        this.settings = {};
        this.scopeDescription = '';
        this.isFileMode = false;
        this.configPath = this.parseConfigArg();
        this.currentMappingIndex = 0;
        this.totalMappings = 0;
        this.currentOriginFolder = '';
        this.interrupted = false;
        this.hashErrors = [];
        this.hashTimeoutMs = 30000;
        this.maxHashSizeBytes = 500*1024*1024;
        this.originMap = new Map();
        this.lastPrintedFolder = '';
        this.setupStopHandlers();
    }

    setupStopHandlers()
    {
        process.on('SIGINT', async () => {
            await this.stop();
        });
        // on Windows, closing the console window emits SIGHUP and the process is killed a few seconds later:
        process.on('SIGHUP', async () => {
            await this.stop();
        });
        // the console or the parent process can be gone already, ignore the output errors so the log is still saved:
        process.stdout.on('error', () => {});
        process.stderr.on('error', () => {});
        if(!process.send){
            return;
        }
        process.on('message', async (message) => {
            if('stop' === message){
                await this.stop();
            }
        });
    }

    async stop()
    {
        if(this.interrupted){
            return;
        }
        this.interrupted = true;
        console.log('\n\nInterrupted by user. Saving progress...');
        await this.writeLogFile();
        console.log('Progress saved. Exiting.');
        process.exit(0);
    }

    parseModifiedTimeThreshold()
    {
        let prefix = '--modified-time-threshold=';
        for(let arg of this.args){
            if(!arg.startsWith(prefix)){
                continue;
            }
            let match = /^(\d+(?:\.\d+)?)(ms|s)?$/.exec(arg.substring(prefix.length).trim());
            if(!match){
                console.error('Invalid '+arg+', use milliseconds (2000) or seconds (2s).');
                process.exit(1);
            }
            return Math.round(Number(match[1])*('s' === match[2] ? 1000 : 1));
        }
        return null;
    }

    resolveModifiedTimeThreshold()
    {
        if(null !== this.cliModifiedTimeThresholdMs){
            return this.cliModifiedTimeThresholdMs;
        }
        let configured = Number(this.settings.modifiedTimeThresholdMs);
        if(undefined !== this.settings.modifiedTimeThresholdMs && Number.isFinite(configured) && 0 <= configured){
            return Math.round(configured);
        }
        return this.defaultModifiedTimeThresholdMs;
    }

    parseTextArg(prefix)
    {
        for(let arg of this.args){
            if(arg.startsWith(prefix)){
                return arg.substring(prefix.length).trim();
            }
        }
        return '';
    }

    parseMappingSelection()
    {
        let prefix = '--mapping=';
        for(let arg of this.args){
            if(!arg.startsWith(prefix)){
                continue;
            }
            let numbers = arg.substring(prefix.length).split(',').map((value) => {
                return Number(value.trim());
            });
            for(let number of numbers){
                if(!Number.isInteger(number) || 1 > number){
                    console.error('Invalid '+arg+', use mapping numbers starting at 1, like --mapping=2 or --mapping=1,3.');
                    process.exit(1);
                }
            }
            return numbers;
        }
        return [];
    }

    selectMappings(allMappings)
    {
        if(0 === allMappings.length){
            console.log('No mappings found. Nothing to sync.');
            process.exit(0);
        }
        for(let number of this.selectedMappings){
            if(allMappings.length < number){
                console.error('There is no mapping #'+number+', the config has '+allMappings.length+' mappings.');
                process.exit(1);
            }
        }
        let selected = [];
        for(let i = 0; i < allMappings.length; i++){
            // an explicit --mapping selection runs those mappings even when they are disabled:
            if(0 < this.selectedMappings.length){
                if(-1 !== this.selectedMappings.indexOf(i+1)){
                    selected.push(allMappings[i]);
                }
                continue;
            }
            if(false === allMappings[i].enabled){
                console.log('Skipping disabled mapping #'+(i+1)+': '+allMappings[i].from);
                continue;
            }
            selected.push(allMappings[i]);
        }
        this.scopeDescription = 0 < this.selectedMappings.length
            ? 'selected #'+this.selectedMappings.join(', #')
            : 'all enabled ('+selected.length+' of '+allMappings.length+')';
        if(0 === selected.length){
            console.log('All mappings are disabled. Nothing to sync.');
            process.exit(0);
        }
        return selected;
    }

    parseConfigArg()
    {
        for(let arg of this.args){
            if(arg.startsWith('--config-files=')){
                let configFile = arg.substring(15);
                this.isFileMode = true;
                return this.resolveConfigPath(configFile);
            }
            if(arg.startsWith('--config=')){
                let configFile = arg.substring(9);
                return this.resolveConfigPath(configFile);
            }
        }
        let syncConfigFiles = path.join(process.cwd(), 'configurations', 'sync-config-files.js');
        if(fs.existsSync(syncConfigFiles)){
            this.isFileMode = true;
            return syncConfigFiles;
        }
        return path.join(process.cwd(), 'configurations', 'sync.config.js');
    }

    resolveConfigPath(configFile)
    {
        let fromCurrentFolder = path.resolve(process.cwd(), configFile);
        if(fs.existsSync(fromCurrentFolder)){
            return fromCurrentFolder;
        }
        let fromConfigurationsFolder = path.join(process.cwd(), 'configurations', configFile);
        if(fs.existsSync(fromConfigurationsFolder)){
            return fromConfigurationsFolder;
        }
        return fromCurrentFolder;
    }

    validateConfig()
    {
        let configExists = fs.existsSync(this.configPath);
        if(!configExists){
            console.error('Config file not found: '+this.configPath);
            process.exit(1);
        }
        let config = require(this.configPath);
        this.settings = config.settings || {};
        if(config.mappings){
            return this.selectMappings(config.mappings || []);
        }
        if(0 < this.selectedMappings.length){
            console.error('--mapping only works with a folder config that has "mappings", not with a file list.');
            process.exit(1);
        }
        // generated file lists are {settings, files: {source: destinations}}, older ones are only that object:
        let fileMap = config.files && 'object' === typeof config.files ? config.files : config;
        let mappings = [];
        for(let srcPath of Object.keys(fileMap)){
            if(fileMap === config && 'settings' === srcPath){
                continue;
            }
            let dstPaths = fileMap[srcPath];
            mappings.push({
                from: srcPath,
                to: Array.isArray(dstPaths) ? dstPaths : [dstPaths]
            });
        }
        if(0 === mappings.length){
            console.log('No mappings found. Nothing to sync.');
            process.exit(0);
        }
        return mappings;
    }

    isGoogleDriveShortcut(filePath)
    {
        let ext = path.extname(filePath).toLowerCase();
        return '.gsheet' === ext || '.gmap' === ext || '.gdoc' === ext || '.gslides' === ext || '.gform' === ext;
    }

    makeRelPath(base, p)
    {
        let rel = path.relative(base, p);
        if('' === rel){
            return '';
        }
        return rel.split(path.sep).join('/');
    }

    async statSafe(p)
    {
        try{
            return await fsp.stat(p);
        }catch(e){
            return false;
        }
    }

    async ensureDir(dir)
    {
        try{
            await fsp.mkdir(dir, { recursive: true });
        }catch(e){
            if('EEXIST' !== e.code){
                throw e;
            }
        }
    }

    async copyOne(src, dst)
    {
        let dstDir = path.dirname(dst);
        await this.ensureDir(dstDir);
        await fsp.copyFile(src, dst);
        let st = await fsp.stat(src);
        try{
            await fsp.utimes(dst, st.atime, st.mtime);
        }catch(e){}
    }

    async removeOne(p)
    {
        try{
            await fsp.unlink(p);
        }catch(e){
            throw e;
        }
    }

    hashFile(p)
    {
        return new Promise((resolve, reject) => {
            let h = crypto.createHash('md5');
            let s = fs.createReadStream(p);
            let done = false;
            let timeoutId = setTimeout(() => {
                if(done){
                    return;
                }
                done = true;
                s.destroy();
                reject(new Error('hash-timeout'));
            }, this.hashTimeoutMs);
            s.on('data', (chunk) => {
                if(done){
                    return;
                }
                h.update(chunk);
            });
            s.on('error', (e) => {
                if(done){
                    return;
                }
                done = true;
                clearTimeout(timeoutId);
                reject(e);
            });
            s.on('end', () => {
                if(done){
                    return;
                }
                done = true;
                clearTimeout(timeoutId);
                resolve(h.digest('hex'));
            });
        });
    }

    pathSegments(rel)
    {
        if('' === rel){
            return [];
        }
        return rel.split('/').filter((x) => { return '' !== x; });
    }

    isHiddenName(name)
    {
        if(0 === name.length){
            return false;
        }
        if('.' === name[0]){
            return true;
        }
        return false;
    }

    isSystemName(name)
    {
        let lower = name.toLowerCase();
        if('system volume information' === lower){
            return true;
        }
        if('$recycle.bin' === lower){
            return true;
        }
        if('desktop.ini' === lower){
            return true;
        }
        if('thumbs.db' === lower){
            return true;
        }
        return false;
    }

    extOf(rel)
    {
        let b = path.basename(rel);
        let idx = b.lastIndexOf('.');
        if(-1 === idx){
            return '';
        }
        return b.substring(idx).toLowerCase();
    }

    matchesFilters(rel, st, opts)
    {
        if(!opts){
            return true;
        }
        let segs = this.pathSegments(rel);
        if(opts.excludeHidden){
            for(let s of segs){
                if(this.isHiddenName(s)){
                    return false;
                }
            }
        }
        if(opts.excludeSystem){
            for(let s of segs){
                if(this.isSystemName(s)){
                    return false;
                }
            }
        }
        let exNames = opts.excludeNames || [];
        if(0 < exNames.length){
            for(let s of segs){
                if(-1 !== exNames.indexOf(s)){
                    return false;
                }
            }
        }
        let includeExt = opts.includeExtensions || [];
        if(0 < includeExt.length){
            let e = this.extOf(rel);
            if(-1 === includeExt.indexOf(e)){
                return false;
            }
        }
        let excludeExt = opts.excludeExtensions || [];
        if(0 < excludeExt.length){
            let e2 = this.extOf(rel);
            if(-1 !== excludeExt.indexOf(e2)){
                return false;
            }
        }
        if(opts.maxSizeBytes && 0 < opts.maxSizeBytes){
            if(st && st.size && opts.maxSizeBytes < st.size){
                return false;
            }
        }
        return true;
    }

    async verifyCopy(src, dst)
    {
        let sst = await this.statSafe(src);
        let dstst = await this.statSafe(dst);
        if(!sst){
            return { ok: false, reason: 'src-missing' };
        }
        if(!dstst){
            return { ok: false, reason: 'dst-missing' };
        }
        if(sst.size !== dstst.size){
            return { ok: false, reason: 'size-mismatch' };
        }
        if(Math.abs(sst.mtimeMs-dstst.mtimeMs) <= this.modifiedTimeThresholdMs){
            return { ok: true, reason: 'ok' };
        }
        let sh;
        let dh;
        try{
            sh = await this.hashFile(src);
            dh = await this.hashFile(dst);
        }catch(e){
            return { ok: false, reason: 'hash-error: '+e.message };
        }
        if(sh !== dh){
            return { ok: false, reason: 'hash-mismatch' };
        }
        return { ok: true, reason: 'hash-ok' };
    }

    printFolderIfChanged(folderPath)
    {
        if(this.lastPrintedFolder !== folderPath){
            if('' !== this.lastPrintedFolder){
                process.stdout.write('\n');
            }
            process.stdout.write('Sync mapped folder: '+folderPath+'\n');
            this.lastPrintedFolder = folderPath;
        }
    }

    async syncFile(srcPath, dstPath)
    {
        if(this.interrupted){
            return;
        }
        if(this.isGoogleDriveShortcut(srcPath)){
            return;
        }
        let srcStat = await this.statSafe(srcPath);
        if(!srcStat){
            this.errors.push({ action: 'stat', src: srcPath, message: 'source file not found' });
            return;
        }
        if(srcStat.isDirectory()){
            return;
        }
        this.filesPlanned += 1;
        let fileDir = path.dirname(srcPath);
        this.printFolderIfChanged(fileDir);
        let fileName = path.basename(srcPath);
        let dstStat = await this.statSafe(dstPath);
        let doCopy = false;
        if(!dstStat){
            doCopy = true;
        }
        if(dstStat && dstStat.isDirectory()){
            this.filesProcessed += 1;
            process.stdout.write('\r'+fileName+' - SKIP (dest is directory)'+' '.repeat(20));
            return;
        }
        if(dstStat){
            if(srcStat.size !== dstStat.size){
                doCopy = true;
            }
            if(!doCopy && srcStat.mtimeMs-dstStat.mtimeMs > this.modifiedTimeThresholdMs){
                if(!this.withHash){
                    doCopy = true;
                }
                if(this.withHash){
                    if(srcStat.size > this.maxHashSizeBytes){
                        doCopy = true;
                        this.hashErrors.push({ file: srcPath, reason: 'file-too-large', size: srcStat.size });
                    }
                    if(!doCopy){
                        let srcHash = '';
                        let dstHash = '';
                        try{
                            process.stdout.write('\rHashing ['+fileName+']: '+this.filesProcessed.toString()+' files...'+' '.repeat(30));
                            srcHash = await this.hashFile(srcPath);
                            dstHash = await this.hashFile(dstPath);
                        }catch(e){
                            doCopy = true;
                            this.hashErrors.push({ file: srcPath, reason: e.message });
                        }
                        if('' !== srcHash && '' !== dstHash && srcHash !== dstHash){
                            doCopy = true;
                        }
                    }
                }
            }
        }
        if(doCopy && this.dryRun){
            this.filesProcessed += 1;
            this.syncedFiles.push({ src: srcPath, dst: dstPath, rel: fileName });
            process.stdout.write('\r'+fileName+' - SYNC (DRY-RUN)'+' '.repeat(20));
            return;
        }
        if(doCopy && !this.dryRun){
            try{
                await this.copyOne(srcPath, dstPath);
                let v = await this.verifyCopy(srcPath, dstPath);
                if(!v.ok){
                    this.errors.push({ action: 'verify', src: srcPath, dst: dstPath, message: v.reason });
                }
                this.syncedFiles.push({ src: srcPath, dst: dstPath, rel: fileName });
            }catch(e){
                this.errors.push({ action: 'copy', src: srcPath, dst: dstPath, message: e.message });
            }
            this.filesProcessed += 1;
            process.stdout.write('\r'+fileName+' - SYNC'+' '.repeat(50));
            return;
        }
        if(!doCopy){
            this.alreadySyncedFiles.push({ src: srcPath, dst: dstPath, rel: fileName });
        }
        this.filesProcessed += 1;
        process.stdout.write('\r'+fileName+' - OK'+' '.repeat(50));
    }

    async processOriginFile(fullPath, originRoot, dest, mapping)
    {
        let rel = this.makeRelPath(originRoot, fullPath);
        if('' === rel){
            return;
        }
        if(this.isGoogleDriveShortcut(fullPath)){
            return;
        }
        let srcStat = await this.statSafe(fullPath);
        if(!srcStat){
            return;
        }
        if(srcStat.isDirectory()){
            return;
        }
        if(!this.matchesFilters(rel, srcStat, mapping)){
            return;
        }
        this.originMap.set(rel, true);
        this.filesPlanned += 1;
        let fileDir = path.dirname(fullPath);
        this.printFolderIfChanged(fileDir);
        let fileName = path.basename(rel);
        let dstPath = path.join(dest, rel);
        let dstStat = await this.statSafe(dstPath);
        let doCopy = false;
        if(!dstStat){
            doCopy = true;
        }
        if(dstStat && dstStat.isDirectory()){
            this.filesProcessed += 1;
            process.stdout.write('\r'+fileName+' - SKIP (dest is directory)'+' '.repeat(20));
            return;
        }
        if(dstStat){
            if(srcStat.size !== dstStat.size){
                doCopy = true;
            }
            if(!doCopy && srcStat.mtimeMs-dstStat.mtimeMs > this.modifiedTimeThresholdMs){
                if(!this.withHash){
                    doCopy = true;
                }
                if(this.withHash){
                    if(srcStat.size > this.maxHashSizeBytes){
                        doCopy = true;
                        this.hashErrors.push({ file: rel, reason: 'file-too-large', size: srcStat.size });
                    }
                    if(!doCopy){
                        let srcHash = '';
                        let dstHash = '';
                        try{
                            process.stdout.write('\rHashing ['+fileName+']: '+this.filesProcessed.toString()+' files...'+' '.repeat(30));
                            srcHash = await this.hashFile(fullPath);
                            dstHash = await this.hashFile(dstPath);
                        }catch(e){
                            doCopy = true;
                            this.hashErrors.push({ file: rel, reason: e.message });
                        }
                        if('' !== srcHash && '' !== dstHash && srcHash !== dstHash){
                            doCopy = true;
                        }
                    }
                }
            }
        }
        if(doCopy && this.dryRun){
            this.filesProcessed += 1;
            this.syncedFiles.push({ src: fullPath, dst: dstPath, rel: rel });
            process.stdout.write('\r'+fileName+' - SYNC (DRY-RUN)'+' '.repeat(20));
            return;
        }
        if(doCopy && !this.dryRun){
            try{
                await this.copyOne(fullPath, dstPath);
                let v = await this.verifyCopy(fullPath, dstPath);
                if(!v.ok){
                    this.errors.push({ action: 'verify', src: fullPath, dst: dstPath, message: v.reason });
                }
                this.syncedFiles.push({ src: fullPath, dst: dstPath, rel: rel });
            }catch(e){
                this.errors.push({ action: 'copy', src: fullPath, dst: dstPath, message: e.message });
            }
            this.filesProcessed += 1;
            process.stdout.write('\r'+fileName+' - SYNC'+' '.repeat(50));
            return;
        }
        if(!doCopy){
            this.alreadySyncedFiles.push({ src: fullPath, dst: dstPath, rel: rel });
        }
        this.filesProcessed += 1;
        process.stdout.write('\r'+fileName+' - OK'+' '.repeat(50));
    }

    async walkOriginAndSync(originRoot, dest, mapping)
    {
        let stack = [originRoot];
        while(0 < stack.length){
            if(this.interrupted){
                break;
            }
            let current = stack.pop();
            let dirents;
            try{
                dirents = await fsp.readdir(current, { withFileTypes: true });
            }catch(e){
                this.errors.push({ action: 'readdir', path: current, message: e.message });
                continue;
            }
            for(let d of dirents){
                if(this.interrupted){
                    break;
                }
                let full = path.join(current, d.name);
                if(d.isDirectory()){
                    stack.push(full);
                    continue;
                }
                if(!d.isFile()){
                    continue;
                }
                await this.processOriginFile(full, originRoot, dest, mapping);
            }
        }
    }

    async scanDestForRemovals(dest, mapping)
    {
        let stack = [dest];
        let removalCount = 0;
        while(0 < stack.length){
            if(this.interrupted){
                break;
            }
            let current = stack.pop();
            let dirents;
            try{
                dirents = await fsp.readdir(current, { withFileTypes: true });
            }catch(e){
                this.errors.push({ action: 'readdir', path: current, message: e.message });
                continue;
            }
            for(let d of dirents){
                if(this.interrupted){
                    break;
                }
                let full = path.join(current, d.name);
                if(d.isDirectory()){
                    stack.push(full);
                    continue;
                }
                if(!d.isFile()){
                    continue;
                }
                let relDf = this.makeRelPath(dest, full);
                if('' === relDf){
                    continue;
                }
                if(this.isGoogleDriveShortcut(full)){
                    continue;
                }
                let dstStat = await this.statSafe(full);
                if(!dstStat){
                    continue;
                }
                if(dstStat.isDirectory()){
                    continue;
                }
                if(!this.matchesFilters(relDf, dstStat, mapping)){
                    continue;
                }
                let existsInOrigin = this.originMap.has(relDf);
                if(existsInOrigin){
                    continue;
                }
                this.filesPlanned += 1;
                this.removedFiles.push({ path: full, rel: relDf });
                let fileDir = path.dirname(full);
                this.printFolderIfChanged(fileDir);
                let fileName = path.basename(relDf);
                if(this.dryRun){
                    this.filesProcessed += 1;
                    process.stdout.write('\r'+fileName+' - RM (DRY-RUN)'+' '.repeat(20));
                    continue;
                }
                try{
                    await this.removeOne(full);
                }catch(e){
                    this.errors.push({ action: 'remove', path: full, message: e.message });
                }
                this.filesProcessed += 1;
                process.stdout.write('\r'+fileName+' - RM'+' '.repeat(20));
                removalCount += 1;
            }
        }
    }

    async syncMappingToDest(mapping, dest)
    {
        this.filesPlanned = 0;
        this.filesProcessed = 0;
        this.originMap.clear();
        if(!this.isFileMode){
            this.lastPrintedFolder = '';
        }
        let originRoot = mapping.from;
        this.currentOriginFolder = originRoot;
        let originExists = fs.existsSync(originRoot);
        if(!originExists){
            console.log('Origin not found: '+originRoot);
            return;
        }
        if(this.isFileMode){
            await this.syncFile(originRoot, dest);
        }
        if(!this.isFileMode){
            await this.walkOriginAndSync(originRoot, dest, mapping);
        }
        if(this.interrupted){
            return;
        }
        if(this.allowRemove && !this.isFileMode){
            let destExists = fs.existsSync(dest);
            if(destExists){
                await this.scanDestForRemovals(dest, mapping);
            }
        }
        if(!this.isFileMode && 0 < this.filesProcessed){
            process.stdout.write('\n');
        }
    }

    async writeLogFile()
    {
        let logsDir = path.join(process.cwd(), 'logs');
        try{
            await this.ensureDir(logsDir);
        }catch(e){}
        let now = new Date();
        let pad2 = (n) => { return (n < 10 ? '0' : '')+n; };
        let stamp = now.getFullYear().toString()+pad2(now.getMonth()+1)+pad2(now.getDate())+'-'+pad2(now.getHours())+pad2(now.getMinutes())+pad2(now.getSeconds());
        let lines = [];
        lines.push('=== SYNC LOG ===');
        lines.push('Timestamp: '+now.toISOString());
        if('' !== this.triggeredBy){
            lines.push('Triggered By: '+this.triggeredBy);
        }
        lines.push('Config: '+path.basename(this.configPath));
        lines.push('Dry Run: '+(this.dryRun ? 'YES' : 'NO'));
        lines.push('Allow Remove: '+(this.allowRemove ? 'YES' : 'NO'));
        lines.push('Hash Enabled: '+(this.withHash ? 'YES' : 'NO'));
        lines.push('Modified Time Threshold: '+this.modifiedTimeThresholdMs.toString()+'ms');
        if('' !== this.scopeDescription){
            lines.push('Mappings: '+this.scopeDescription);
        }
        if(this.interrupted){
            lines.push('Status: INTERRUPTED');
        }
        lines.push('');
        if(0 < this.hashErrors.length){
            lines.push('--- HASH ERRORS ('+this.hashErrors.length.toString()+') ---');
            for(let err of this.hashErrors){
                let msg = 'file='+err.file+' | reason='+err.reason;
                if(err.size){
                    msg = msg+' | size='+err.size.toString();
                }
                lines.push(msg);
            }
            lines.push('');
        }
        if(0 < this.alreadySyncedFiles.length){
            lines.push('--- ALREADY SYNCED FILES ('+this.alreadySyncedFiles.length.toString()+') ---');
            for(let item of this.alreadySyncedFiles){
                lines.push('OK | '+item.rel+' | '+item.src+' -> '+item.dst);
            }
            lines.push('');
        }
        if(0 < this.syncedFiles.length){
            lines.push('--- UPDATED FILES ('+this.syncedFiles.length.toString()+') ---');
            for(let item of this.syncedFiles){
                lines.push('SYNC | '+item.rel+' | '+item.src+' -> '+item.dst);
            }
            lines.push('');
        }
        if(0 < this.removedFiles.length){
            lines.push('--- REMOVED FILES ('+this.removedFiles.length.toString()+') ---');
            for(let item of this.removedFiles){
                lines.push('RM | '+item.rel+' | '+item.path);
            }
            lines.push('');
        }
        if(0 < this.errors.length){
            lines.push('--- ERRORS ('+this.errors.length.toString()+') ---');
            for(let err of this.errors){
                let parts = [];
                parts.push('action='+(err.action || ''));
                if(err.src){
                    parts.push('src='+err.src);
                }
                if(err.dst){
                    parts.push('dst='+err.dst);
                }
                if(err.path){
                    parts.push('path='+err.path);
                }
                parts.push('message='+(err.message || ''));
                lines.push(parts.join(' | '));
            }
            lines.push('');
        }
        lines.push('=== END LOG ===');
        try{
            let logFile = await this.writeNewFile(logsDir, 'sync-'+stamp, '.log', lines.join('\n'));
            console.log('Log file: '+logFile);
            return logFile;
        }catch(e){
            console.log('Failed to write log file: '+e.message);
            return false;
        }
    }

    async writeNewFile(folder, baseName, extension, content)
    {
        // scheduled jobs run in parallel and can finish in the same second, never overwrite another run's file:
        for(let attempt = 1; attempt < 100; attempt++){
            let filePath = path.join(folder, baseName+(1 === attempt ? '' : '-'+attempt)+extension);
            try{
                await fsp.writeFile(filePath, content, {encoding: 'utf8', flag: 'wx'});
                return filePath;
            }catch(e){
                if('EEXIST' !== e.code){
                    throw e;
                }
            }
        }
        throw new Error('No free file name for '+baseName+extension);
    }

    async run()
    {
        let mappings = this.validateConfig();
        this.modifiedTimeThresholdMs = this.resolveModifiedTimeThreshold();
        let totalDestinations = 0;
        for(let mapping of mappings){
            let toList = mapping.to || [];
            totalDestinations += toList.length;
        }
        this.totalMappings = totalDestinations;
        console.log('Using config: '+this.configPath);
        console.log('Mode: '+(this.isFileMode ? 'File-by-file' : 'Folder scanning'));
        if(this.isFileMode){
            console.log('Total mappings: '+this.totalMappings.toString());
        }
        if(this.withHash){
            console.log('Hash comparison: ENABLED');
            console.log('Hash timeout: '+this.hashTimeoutMs.toString()+'ms');
            console.log('Max hash size: '+(this.maxHashSizeBytes/1024/1024).toString()+'MB');
        }
        if(!this.withHash){
            console.log('Hash comparison: DISABLED (use --with-hash to enable)');
        }
        console.log('Modified time threshold: '+this.modifiedTimeThresholdMs.toString()+'ms');
        if('' !== this.scopeDescription){
            console.log('Mappings: '+this.scopeDescription);
        }
        for(let mapping of mappings){
            if(this.interrupted){
                break;
            }
            let from = mapping.from;
            let toList = mapping.to || [];
            if(0 === toList.length){
                continue;
            }
            for(let dest of toList){
                if(this.interrupted){
                    break;
                }
                this.currentMappingIndex += 1;
                await this.syncMappingToDest(mapping, dest);
            }
        }
        if(this.interrupted){
            // stop() saves the log and exits:
            return;
        }
        if(this.isFileMode && '' !== this.lastPrintedFolder){
            process.stdout.write('\n');
        }
        let durationMs = Date.now()-this.startTime;
        console.log('Sync finished in '+durationMs.toString()+'ms');
        if(0 < this.hashErrors.length){
            console.log('Hash errors: '+this.hashErrors.length.toString()+' (see log for details)');
        }
        if(0 < this.errors.length){
            console.log('Errors: '+this.errors.length.toString()+' (see log for details)');
        }
        await this.writeLogFile();
        if(process.connected){
            process.disconnect();
        }
    }

}

let synchronizer = new RunSync();
synchronizer.run().catch((e) => {
    console.error('Fatal: '+e.message);
    process.exit(1);
});

module.exports.RunSync = RunSync;
