/**
 * File Synchronization Script
 *
 * One-way sync from laptop (source) to external disks (destinations).
 * Source files are NEVER modified or deleted.
 *
 * USAGE:
 * 1. Create configurations/sync.config.js (see config format below), or pass a config with --config / --config-files
 * 2. Run: node run-sync.js
 * 3. Optional flags:
 *    - node run-sync.js --dry-run (preview changes without applying)
 *    - node run-sync.js --allow-remove (delete files in dest that don't exist in source)
 *    - node run-sync.js --with-hash (enable hash comparison for same-size files)
 *    - node run-sync.js --config=custom.config.js (use custom folder config file)
 *    - node run-sync.js --config-files=YYYY-MM-DD-HH-MM-SS-sync-config-files.js (use file mapping config)
 *    - node run-sync.js --modified-time-threshold=2s (how much newer the source must be to count as changed,
 *      in milliseconds or with an "s"/"ms" suffix; overrides settings.modifiedTimeThresholdMs from the config;
 *      default 2s, for FAT32/exFAT disks that keep 2 second times)
 *    - node run-sync.js --config=inspect.config.js --mapping=2 (or --mapping=1,3) syncs only those mappings of a
 *      folder config, numbered from 1 in the config order. Without it, mappings with "enabled: false" are skipped.
 *    - node run-sync.js --triggered-by="schedule: general schedule" (written in the log header, used by the scheduler)
 *
 * Logs are never overwritten: when two runs finish in the same second, the second log gets a "-2" suffix.
 *
 * CONFIG PATHS:
 * - --config and --config-files are resolved from the current folder first, then from the "configurations" folder,
 *   where run-inspect-folders.js saves the generated configs.
 *
 * AUTO-DETECTION (when no --config or --config-files is given):
 * - If configurations/sync-config-files.js exists: syncs only listed files (file-by-file mode)
 * - Otherwise: uses configurations/sync.config.js and scans folders normally
 *
 * FILE MAPPING CONFIG (sync-config-files.js, as generated by run-inspect-folders.js):
 * module.exports = {
 *     settings: {modifiedTimeThresholdMs: 2000},
 *     files: {
 *         "C:\\source\\file.pdf": ["X:\\backup-1\\file.pdf", "Y:\\backup-2\\file.pdf"],
 *         "C:\\source\\other.pdf": "Y:\\backup-2\\other.pdf"
 *     }
 * };
 * Older file lists without "settings" and "files" (only the source to destinations object) still work.
 *
 * STOPPING:
 * - Ctrl+C, closing the console window, or the "stop" IPC message when started with child_process.fork()
 *   (used by the web tool).
 * - All of them save the log before exiting.
 *
 * CONFIGURATION (configurations/sync.config.js, settings is optional):
 * module.exports = {
 *     settings: {modifiedTimeThresholdMs: 2000},
 *     mappings: [
 *         {
 *             from: "C:\\source\\activities",
 *             to: ["Y:\\backup-2\\activities"],
 *             enabled: true,
 *             includeExtensions: [".fit", ".gpx"],
 *             excludeExtensions: [".tmp"],
 *             maxSizeBytes: 0,
 *             excludeHidden: true,
 *             excludeSystem: true,
 *             excludeNames: ["node_modules", ".git"]
 *         }
 *     ]
 * };
 */

const { RunSync } = require('./lib/sync/run-sync');

let synchronizer = new RunSync({args: process.argv.slice(2), rootPath: process.cwd()});
synchronizer.run().catch((e) => {
    console.error('Fatal: '+e.message);
    process.exit(1);
});
